### PR TITLE
Logs: add verbose mode to display context for each entry log

### PR DESCRIPTION
**Pull request by piotrze**
```pos-cli logs env``` will have context for each log entry.
There is a `--quiet` option that will print only lot message with timestamp.

### CODE REVIEW

**Comment by pavelloz** [comment]
Shouldnt it be default?

**Comment by piotrze** [comment]
@pavelloz It is verbose

image

We might change the formatting in `pos-cli` client

**Comment by Slashek** [comment]
I like the idea of verbose being the default

**Comment by pavelloz** [comment]
Hmmm, some formatting to make it more compact and i think default wouldnt hurt.
BTW. 
image  - this path looks very weird

**Comment by piotrze** [comment]
@pavelloz Improved formatting
image

**Comment by pavelloz** [comment]
I propose to format this thing as json not as ruby magic rocket syntax ;)

**Comment by pavelloz** [comment]
👍

**Comment by pavelloz** [comment]
Im wondering if the whole url is necessary - after all you are running logs command for one environement, so it is very repetitive and obvious. Path should be enough right?

**Comment by piotrze** [comment]
@pavelloz I used a `path`

**Pull request merged**
