### PR TITLE
Do not sync template values

### PR DESCRIPTION
**Pull request by andrew-3**
Fix for: https://near-me.atlassian.net/browse/NMS-5036?oldIssueView=true

Looks like we shouldn't attempt to sync template-values.json as it results in an error.

Thanks

### CODE REVIEW

**Comment by andrew-3** [comment]
@pavelloz Does it even have a place server-side? From my understanding its role is to fill in template values when the files are deployed or synced. And deploying it "works" probably because it's ignoring it.

Thanks

**Comment by pavelloz** [comment]
I dont know to be honest. Code ownership isnt a good thing, because owner leaves sooner or later. :)

**Comment by andrew-3** [comment]
@pavelloz OK, then I'm merging this. It doesn't affect the existing behavior of templates filling in values on deploy/sync and it's an improvement in that the error will no longer be shown on sync. I also couldn't find backend code related to this.

Thanks

**Comment by pavelloz** [comment]
Not showing an error isnt always an improvement.

**Comment by andrew-3** [comment]
Yes, ok, I meant that according to everything I could find this file should be ignored.

**Pull request merged**
