### PR TITLE
Add file size to assets manifest

### PR DESCRIPTION
**Pull request by andrew-3**
Added file size to assets manifest

Thanks!

### CODE REVIEW

**Comment by piotrze** [comment]
@andrew-3 Why we need this?

**Comment by andrew-3** [comment]
@piotrze Because Siteglide want to see how much space an asset takes and we don't want expensive operations to do it (this works in tandem with the corresponding backend changes). Also @Slashek suggested this is the best way to do it.

Thanks!

**Comment by andrew-3** [comment]
@piotrze PS: From the card:

"What we would like is that admin_assets returns an integer such as file_size so that within our file manager people can view/sort by file size and then if they are nearing limits, know which files are larger to delete"

**Review by Slashek — APPROVED** [review]

**Review by piotrze — APPROVED** [review]

**Comment by piotrze** [comment]
@andrew-3 Fix tests please.

**Pull request merged**
